[workspace]
members = [
    "sample000",
    "sample001",
    "sample002",
    "sample003",
    "sample004",
    "sample005",
    "sample006",
    "sample4j"
]

# https://substrate.stackexchange.com/questions/9011/warning-some-crates-are-on-edition-2021-which-defaults-to-resolver-2
resolver = "2"
